### ISSUE TITLE
Run as non-root user

### ISSUE THREAD

**Issue by degudejung** [alcapone1933/docker-ddns-ipv64#9]
Hi,
thanks for this nice piece of code!

I saw that your PUID und PGID parameters will not make the container run as that specific user. On the host the process will still be run as root. I would prefer running as a non-root user.

When forcing Docker to run the container as non-root, like with the "user: 1000:1000" specification in the docker compose file, the script will not work, since it lacks the necessary rights inside the container when accessing /etc/cron.d/container_cronjob or /data/updip.txt.

Would you consider adding the capability of running the container as a different / non-root user?

**Comment by alcapone1933** [comment]
The challenge here is that I can't cover all cases where the Docker container is started with a specific user, and you want to change the user ID (UID) and group ID (GID).

Currently, the root user is only responsible for adjusting the directories for logs with the correct UID and GID.

Otherwise, every day, new issues arise where someone wants to change their UID and GID or use a different user.

At the end of the day, it’s just a Docker container running a cron job. If you need more specific customizations, you would have to build your own container.

**Comment by degudejung** [comment]
I appreciate the detailed response and that absolutely makes sense to me.

In the end, maybe the cron job is the thing here for me. I am also running [ZoeyVid's container](https://github.com/ZoeyVid/ipv64-updater) now because they bypass the root/cron challenge be just sleeping the script itself. I don't know if that's considered bad coding (I'm just a user) but it works and does not appear to consume more resources. Now, if they had some very basic logging output - yours is great - then that would probably be my perfect combination.
